name: Release

on:
  push:
    tags:
      - "v*" # v1.0.0 のように、vから始まるタグがpushされた時に動く

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # これが重要！GitHubにリリースを作成する権限を与えます
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 全ての履歴を取得してリリースノートを正確に生成

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true # 自動で変更点（PRなど）をまとめてくれる
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 標準で備わっているトークンを使用
